[package]
name = "abi_stable"
version = "0.8.4"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition="2018"
license = "MIT/Apache-2.0"
description = "For doing Rust-to-Rust ffi,writing libraries loaded at program startup."
documentation = "https://docs.rs/abi_stable/"
readme="../readme.md"
keywords = ["ffi","data-structures"]
categories = ["data-structures","rust-patterns"]
repository = "https://github.com/rodrimati1992/abi_stable_crates/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../readme.md", 
    "../APACHE_license", 
    "../MIT_license"
]

[badges]
travis-ci = { repository =  "rodrimati1992/abi_stable_crates/" }

[features]
default = ["channels","serde_json"]

rust_1_36=[]

rust_1_38=["rust_1_36"]

rust_1_39=["rust_1_38","abi_stable_derive/rust_1_39"]

# Enables stuff that requires const generics,use this once const generics are stabilized.
const_params=[]

# Enables all nightly features.
all_nightly=[
    "nightly_const_params",
]

# Enables stuff that requires const generics(in nightly Rust).
nightly_const_params=[]

# Test features,only used internally.
only_new_tests=[]
sabi_trait_examples=[]
nonexhaustive_examples=[]

channels=["crossbeam-channel"]


[dependencies]
abi_stable_derive= {version="0.8.4",path="../abi_stable_derive"}
abi_stable_shared= {version="0.8.0",path="../abi_stable_shared"}
serde          = { version = "1.0.98", features = ["derive"] }
serde_derive   = "1.0.98"
libloading     = "0.5.2"
parking_lot    = "0.9.0"
lock_api       = "0.3.1"
generational-arena = "0.2.2"
crossbeam-channel = { version = "0.3.9", optional = true }
serde_json = { version = "1.0.40", features = ["raw_value"], optional = true }

[dependencies.core_extensions]
default_features=false
features=["std"]
version="0.1.8"

[dev-dependencies]
bincode = "1.1.4"
crossbeam-utils = "0.6.6"
serde_json = { version = "1.0.40", features = ["raw_value"] }
rand = "0.7.0"
criterion = "0.2.11"
fnv = "1.0.6"

[build-dependencies]
rustc_version = "0.2"
